### ISSUE TITLE
How can I install BigVis on Mac OSX 10.7, R version 3.1.1??

### ISSUE THREAD

**Issue by MaryamIdris** [hadley/bigvis#31]
I have searched all over the internet and posted questions but none has solved my problem. I am simply trying to install BigVis on my computer (Mac OSX 10.7). I have installed XCode and command line tools but when I run:

install.packages('devtools')
library(devtools)
devtools::install_github("bigvis")

I get the following error:
    Error in username %||% getOption("github.user") %||% stop("Unknown username.") : 
    Unknown username.

I then try again with:
    install.packages('devtools')
    library(devtools)
    devtools::install_github("hadley/bigvis")

But I get a new type of error. This one:
    cc1: error: /usr/local/include: Permission denied
    cc1: error: /usr/local/include: Permission denied
    make: *** [reassign.o] Error 1
    ERROR: compilation failed for package ‘testthat’
    * removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/testthat’
    * restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/testthat’
    Error: Command failed (1)

I don't understand what is going on and what am I to do now?!?!!

**Comment by nihakue** [comment]
Take a look at #33 , This is an issue with the version of Rcpp being used.

**Comment by hadley** [comment]
Should be fixed now
