### ISSUE TITLE
Can't install with Rcpp 0.11.4

### ISSUE THREAD

**Issue by AdeleC** [hadley/bigvis#33]
On Windows 7 with 
R-3.1.2
Rtools 3.1.0.1942  
RStudio
Rcpp 0.11.4

I could not install bigvis:

> devtools::install_github("hadley/bigvis")
Downloading github repo hadley/bigvis@master
Installing bigvis
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/Adele/AppData/Local/Temp/RtmpoHyKvh/devtoolsd3c2658b23/hadley-bigvis-1cdfdc2"  \
  --library="C:/Users/Adele/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'bigvis' ...
** libs

*** arch - i386
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I../inst/include   -I"C:/Users/Adele/Documents/R/win-library/3.1/Rcpp/include" -I"C:/Users/Adele/Documents/R/win-library/3.1/BH/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c BigVis.cpp -o BigVis.o

LINES DELETED HERE

g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I../inst/include   -I"C:/Users/Adele/Documents/R/win-library/3.1/Rcpp/include" -I"C:/Users/Adele/Documents/R/win-library/3.1/BH/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c group.cpp -o group.o
In file included from C:/Users/Adele/Documents/R/win-library/3.1/Rcpp/include/Rcpp.h:40:0,
                 from group.cpp:1:
C:/Users/Adele/Documents/R/win-library/3.1/Rcpp/include/Rcpp/Fast.h: In constructor 'Rcpp::Fast<VECTOR>::Fast(const VECTOR&) [with VECTOR = Rcpp::Vector<14, Rcpp::PreserveStorage>]':
group-hex.hpp:23:48:   instantiated from here
C:/Users/Adele/Documents/R/win-library/3.1/Rcpp/include/Rcpp/Fast.h:31:55: error: invalid conversion from 'Rcpp::Vector<14, Rcpp::PreserveStorage>::const_iterator {aka const double*}' to 'Rcpp::Fast<Rcpp::Vector<14, Rcpp::PreserveStorage> >::value_type* {aka double*}' [-fpermissive]
make: *** [group.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="bigvis.dll" OBJECTS="BigVis.o BinnedVector.o BinnedVectors.o RcppExports.o Summary2d.o condense.o double-diff-sum.o frange.o group.o lowerBound.o smooth-nd.o stats.o summary.o"' had status 2
ERROR: compilation failed for package 'bigvis'
* removing 'C:/Users/Adele/Documents/R/win-library/3.1/bigvis'
Error: Command failed (1)

The problem was fixed when I installed Rcpp 0.11.3.

Adele

**Comment by hadley** [comment]
Should be fixed now
