### ISSUE TITLE
Can't install bigvis in Linux

### ISSUE THREAD

**Issue by linyenheng** [hadley/bigvis#34]
I am trying to install bigvis. I had follow most of the discussion, but it still doesn't work

The error message:

> install_github('hadley/bigvis')
Downloading github repo hadley/bigvis@master
Installing bigvis
'/home/linyenheng/bin/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpafybKD/devtools392a1b514819/hadley-bigvis-1cdfdc2'  \
  --library='/home/linyenheng/bin/lib64/R/library' --install-tests 

* installing *source* package ‘bigvis’ ...
** libs
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c BigVis.cpp -o BigVis.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c BinnedVector.cpp -o BinnedVector.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c BinnedVectors.cpp -o BinnedVectors.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c Summary2d.cpp -o Summary2d.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c condense.cpp -o condense.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c double-diff-sum.cpp -o double-diff-sum.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c frange.cpp -o frange.o
g++ -I/home/linyenheng/bin/lib64/R/include -DNDEBUG -I../inst/include -I/usr/local/include -I"/home/linyenheng/bin/lib64/R/library/Rcpp/include" -I"/home/linyenheng/bin/lib64/R/library/BH/include"   -fpic  -g -O2  -c group.cpp -o group.o
In file included from /home/linyenheng/bin/lib64/R/library/Rcpp/include/Rcpp.h:40,
                 from group.cpp:1:
/home/linyenheng/bin/lib64/R/library/Rcpp/include/Rcpp/Fast.h: In constructor ‘Rcpp::Fast<VECTOR>::Fast(const VECTOR&) [with VECTOR = Rcpp::Vector<14, Rcpp::PreserveStorage>]’:
group-hex.hpp:23:   instantiated from here
/home/linyenheng/bin/lib64/R/library/Rcpp/include/Rcpp/Fast.h:31: error: invalid conversion from ‘const Rcpp::traits::storage_type::type*’ to ‘Rcpp::traits::storage_type::type*’
make: *** [group.o] Error 1
ERROR: compilation failed for package ‘bigvis’
* removing ‘/home/linyenheng/bin/lib64/R/library/bigvis’
Error: Command failed (1)

Thank You

**Comment by AdeleC** [comment]
This looks like it might be the same problem I was having. Do you have Rcpp 0.11.4? If so, uninstall it and install Rcpp 0.11.3 from CRAN and see if that works.

**Comment by linyenheng** [comment]
Yes, I uninstall the Rcpp 0.11.4 and install Rcpp 0.11.3, and it work now.
Thank you

**Comment by hadley** [comment]
Should be fixed now
