### ISSUE TITLE
Unable to install bigvis on Mac RStudio

### ISSUE THREAD

**Issue by BalachanderGS** [hadley/bigvis#35]
Version Details:
---------------------
platform       x86_64-apple-darwin10.8.0   
arch           x86_64                      
os             darwin10.8.0                
system         x86_64, darwin10.8.0        
status                                     
major          3                           
minor          1.0                         
year           2014                        
month          04                          
day            10                          
svn rev        65387                       
language       R                           
version.string R version 3.1.0 (2014-04-10)
nickname       Spring Dance

Installed packages
---------------------------
install.packages("Rcpp", type = "source")
.. trying URL 'http://cran.rstudio.com/src/contrib/Rcpp_0.11.5.tar.gz'

devtools::has_devel()
[1] TRUE

Verified that RCpp is working correctly
> library(Rcpp)
> cppFunction('
+   int one() {
+     return 1;
+   }
+ ')
> one()
[1] 1

Error:
---------
> devtools::install_github("hadley/bigvis")

In file included from group.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp.h:40:
/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/Fast.h:31:38: error: cannot initialize a member subobject of type 'value_type *' (aka 'double *') with an rvalue of type 'const_iterator' (aka 'const double *')
    Fast( const VECTOR& v_) : v(v_), data( v_.begin() ){}
                                     ^     ~~~~~~~~~~
./group-hex.hpp:22:10: note: in instantiation of member function 'Rcpp::Fast<Rcpp::Vector<14, PreserveStorage> >::Fast' requested here
       : x_(x), y_(y), x_width_(x_width), x_origin_(x_origin), 
         ^
1 error generated.
make: *** [group.o] Error 1
ERROR: compilation failed for package ‘bigvis’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/bigvis’
Error: Command failed (1)

**Comment by hadley** [comment]
Should be fixed now
