### ISSUE TITLE
hadley/bigvis installation issues

### ISSUE THREAD

**Issue by somordha** [hadley/bigvis#37]
Hi folks, I've been trying to install bigvis but to no avail. 
Tried solutions at Stackoverflow, reinstalling Rccp, Rtools and so on.
Can anyone help? Here's the error. 

> devtools::install_github('hadley/bigvis')
Downloading github repo hadley/bigvis@master
Installing bigvis
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL '/tmp/RtmpBrMC0O/devtools4c14aefc35b/hadley-bigvis-1cdfdc2'  \
  --library='/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘bigvis’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c BigVis.cpp -o BigVis.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c BinnedVector.cpp -o BinnedVector.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c BinnedVectors.cpp -o BinnedVectors.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Summary2d.cpp -o Summary2d.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c condense.cpp -o condense.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c double-diff-sum.cpp -o double-diff-sum.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c frange.cpp -o frange.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c group.cpp -o group.o
In file included from /home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp.h:40,
                 from group.cpp:1:
/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Fast.h: In constructor ‘Rcpp::Fast<VECTOR>::Fast(const VECTOR&) [with VECTOR = Rcpp::Vector<14, Rcpp::PreserveStorage>]’:
group-hex.hpp:23:   instantiated from here
/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Fast.h:31: error: invalid conversion from ‘const double*’ to ‘double*’
make: *** [group.o] Error 1
ERROR: compilation failed for package ‘bigvis’
* removing ‘/home/stephen.moore/R/x86_64-pc-linux-gnu-library/3.2/bigvis’
Error: Command failed (1)

**Comment by hadley** [comment]
Should be fixed now

**Comment by somordha** [comment]
Hadley,

That’s absolutely brilliant, thanks so much.

Steve
