### ISSUE TITLE
Error when compiling in R

### ISSUE THREAD

**Issue by santigt** [hadley/bigvis#38]
~/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Fast.h:31:55: error: invalid conversion from ‘Rcpp::Vector<14, Rcpp::PreserveStorage>::const_iterator {aka const double*}’ to ‘Rcpp::Fast<Rcpp::Vector<14, Rcpp::PreserveStorage> >::value_type* {aka double*}’ [-fpermissive]
     Fast( const VECTOR& v_) : v(v_), data( v_.begin() ){}

**Comment by hadley** [comment]
Fixed now
